POST http://node-do-zero-ian.onrender.com/videos
Content-Type: application/json

{
    "title": "Node video ian ",
    "describe": "1olá",
    "duration": 120
}

###

GET http://node-do-zero-ian.onrender.com/videos

###

PUT http://node-do-zero-ian.onrender.com/videos/77a050ed-e7c0-4903-9981-2bf2253469bf
Content-Type: application/json

{
    "title": "video Ian Karel",
    "describe": "esse video é maneiro",
    "duration": 128
}

###

DELETE http://node-do-zero-ian.onrender.com/videos/77a050ed-e7c0-4903-9981-2bf2253469bf